import fs from "fs-extra";
import { createHash, createHmac } from "node:crypto";

// A verifiable-delivery receipt: the SHA256 of the exact PDF bytes the buyer received, plus an
// optional HMAC signature proving THIS server issued that hash (so a buyer can later prove the file
// they hold is the one they paid for, unaltered). Signing is enabled only when RECEIPT_SECRET is set;
// without it the receipt still carries the hash, just unsigned. Best-effort — a hashing failure
// returns null rather than failing the comic.
const COMMERCIAL_LICENSE =
  "Commercial use permitted. The buyer who paid for this comic owns full commercial rights to the delivered pages and PDF/CBZ, including resale, print, and publication. Generated by LifeComic.";

export function commercialLicense() {
  return COMMERCIAL_LICENSE;
}

/**
 * Builds a delivery receipt for a finished comic. `pdfPath` is the LOCAL file path (hashed before any
 * cleanup/upload). `meta` carries context folded into the signed payload (id, title). Returns
 * { comicId, title, sha256, algo, issuedAt, license, signature? } or null on failure.
 */
export async function buildReceipt(pdfPath, meta = {}) {
  if (!pdfPath) return null;
  try {
    const bytes = await fs.readFile(pdfPath);
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    const receipt = {
      comicId: meta.id ?? null,
      title: meta.title ?? null,
      sha256,
      algo: "sha256",
      issuedAt: new Date().toISOString(),
      license: COMMERCIAL_LICENSE,
    };
    const secret = process.env.RECEIPT_SECRET;
    if (secret) {
      // Sign the stable core fields so a verifier can recompute the HMAC from the receipt + the
      // server's published key. Order is fixed to keep the signed string deterministic.
      const core = `${receipt.comicId}|${receipt.sha256}|${receipt.issuedAt}`;
      receipt.signature = createHmac("sha256", secret).update(core).digest("hex");
      receipt.signatureScheme = "hmac-sha256";
    }
    return receipt;
  } catch {
    return null;
  }
}
